collections_config:
  blog:
    path: blog
    output: true
    name: Entradas del Blog
    icon: article

# Esto activa el editor para que el m√©dico pueda escribir
_enabled_editors:
  - content
  - visual
