backend:
  name: github
  repo: "alexwrlo-dot/medico-homeopata-alex" # <--- ¡TU USUARIO/REPO AQUÍ!
  branch: main # Rama principal (puede ser 'master')

media_folder: "images/uploads"
public_folder: "/images/uploads"

# Esto permite que el cliente vea el diseño real mientras escribe
site_url: "https://tu-dominio-en-cloudflare.com"

collections:
  - name: "blog"
    label: "Artículos"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Descripción Corta", name: "description", widget: "text"}
      - {label: "Imagen Principal", name: "image", widget: "image", required: false}
      - {label: "Cuerpo del Artículo", name: "body", widget: "markdown"}
