backend:
  name: git-gateway
  branch: main # O 'master', tu rama principal

media_folder: "images/uploads" # Dónde se guardan las fotos que sube el cliente
public_folder: "/images/uploads" # Dónde las busca el HTML

collections:
  - name: "blog" # Nombre interno
    label: "Artículos" # Lo que ve el cliente
    folder: "blog" # La carpeta donde tienes tus .md actuales
    create: true # Permite crear nuevos
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Nombre del archivo
    fields: # Los campos que rellenará el cliente
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen Destacada", name: "thumbnail", widget: "image", required: false}
      - {label: "Cuerpo", name: "body", widget: "markdown"}
