backend:
  name: github
  repo: "alexwrlo-dot/medico-homeopata-alex" # Asegúrate que esto es correcto
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: "https://medico-homeopata-alex.pages.dev" # Tu URL de Cloudflare

collections:
  - name: "blog"
    label: "Artículos"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen Principal", name: "image", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
