backend:
  name: git-gateway
  branch: main # Revisa si tu rama es 'main' o 'master'

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Artículos Médicos"
    folder: "blog" # Carpeta donde se guardarán los posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen de Portada", name: "thumbnail", widget: "image"}
      - {label: "Contenido del Blog", name: "body", widget: "markdown"}